### ISSUE TITLE
Issue with `from icecube.icetray import I3Tray` in container

### ISSUE THREAD

**Issue by mlincett** [icecube/skywriter#13]
When running against a modern IceTray installation one gets a warning about `from I3Tray import I3Tray` [being deprecated](https://docs.icecube.aq/icetray/main/projects/icetray/I3Tray.html).

However in CI `from icecube.icetray import I3Tray` fails due to `I3Tray` not having an `Add` attribute.

Currently I had to revert PR #7 to the old-style import for the sake of CI testing.

**Comment by mlincett** [comment]
@dsschult any suggestion?

**Comment by dsschult** [comment]
It looks like the docker image is at least 6 months old, and you should use the `icetray-prod-current-ubuntu22.04-X64` tag.

**Comment by dsschult** [comment]
I'd probably ask @briedel why the `-X64` got added to the tag name, and the generic tag no longer works.

**Comment by kjmeagher** [comment]
also that warning is completely harmless, but you should upgrade to the latest icetray

**Comment by mlincett** [comment]
Will be fixed in #15 , thanks to all for the inputs!
